// ─── 카테고리 & 법규 ──────────────────────────────────────────────

export type RuleType = "PROHIBITED" | "RESTRICTED" | "REQUIRES_CERTIFICATION" | "ALLOWED";
export type LegalStatus = "CLEAR" | "WARNING" | "BLOCKED";
export type InfraType =
  | "SHARED_KITCHEN"
  | "CERTIFIED_FACILITY"
  | "HOME_KITCHEN"
  | "COLD_CHAIN"
  | "POPUP_STORE"
  | "WAREHOUSE"
  | "STUDIO";

export type DocumentType =
  | "BUSINESS_REGISTRATION"
  | "PRODUCT_MANUFACTURING_REPORT"
  | "LABEL_DRAFT"
  | "HYGIENE_EDUCATION_CERTIFICATE";

export interface LicenseItem {
  licenseId: string;
  licenseName: string;
  issuingAuthority: string;
  isMandatory: boolean;
  estimatedDays: number;
  onlineApplicationUrl?: string;
  requiredDocuments: string[];
}

export interface IngredientRule {
  ingredientName: string;
  ruleType: RuleType;
  restriction?: string;
  legalBasis?: string;
  safetyNote?: string;
  alternativeSuggestion?: string;
}

export interface InfraRequirement {
  infraType: InfraType;
  description: string;
  isMandatory: boolean;
}

export interface OfflineCategory {
  categoryId: string;
  categoryName: string;
  industryGroup: string;           // 대분류 (식품·음료 / 패션·섬유 / ...)
  keywords: string[];              // NLP 매칭용 키워드
  governingLaw: string[];
  requiredLicenses: LicenseItem[];
  prohibitedIngredients: IngredientRule[];
  requiredInfrastructure: InfraRequirement[];
  mandatoryLabelFields: string[];
  autoGeneratedDocuments: DocumentType[];
  notes?: string;                  // 특이사항 (법적 회색지대 등)
}

// ─── 트리아지 엔진 입출력 ─────────────────────────────────────────

export interface IdeaInput {
  sessionId: string;
  rawText: string;
  detectedQuantity?: number;
}

export interface TriageResult {
  sessionId: string;
  legalStatus: LegalStatus;
  matchedCategory: OfflineCategory;
  matchScore: number;
  flaggedIngredients: IngredientRule[];
  alternativeSuggestion?: string;
  // 복수 카테고리 해당 시 (예: 앞치마 어린이용)
  secondaryCategories?: OfflineCategory[];
  lawApiLastChecked?: string;      // 법제처 API 마지막 확인일
}

// ─── 사업 기본 정보 (Step 0) ─────────────────────────────────────

export type BusinessType = "sole" | "corporation" | "undecided";
export type SalesChannel = "offline_only" | "online_only" | "both" | "undecided";
export type BusinessMethod = "self_manufacture" | "import_resell" | "oem" | "popup";

export interface BusinessInfo {
  hasBusinessName: boolean;
  businessName?: string;
  needsTrademark?: boolean;
  businessType: BusinessType;
  region: string;
  salesChannel: SalesChannel;
  hasPhysicalStore: boolean;
  quantity?: number;
  businessMethod: BusinessMethod;    // 사업 방식 (직접제조 / 수입판매 / OEM / 팝업)
}

// ─── 세션 (localStorage 저장) ────────────────────────────────────

export interface BuilderSession {
  sessionId: string;
  rawText: string;
  createdAt: string;
  currentStep: 0 | 1 | 2 | 3 | 4 | 5;
  businessInfo?: BusinessInfo;
  triage?: TriageResult;
  budget?: BudgetResult;
  labelFields?: Record<string, string>;
}

export interface BudgetResult {
  fixedCost: number;
  variableCostPerUnit: number;
  quantity: number;
  totalCost: number;
  recommendedRetailPrice: number;
}
